version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgre:example@postgres:5432/dev-db
    ports:
      - "3000:3000"
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dev-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
